# -*- coding: utf-8 -*-
"""Google Translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uySZyAf64tLA-UeAhvCfppVM7iIT2O_j
"""

!pip install deep-translator tqdm openpyxl -q

import pandas as pd
from deep_translator import GoogleTranslator
from tqdm.notebook import tqdm

# 1. Load file
df = pd.read_csv("/content/sample_data/full_data.csv")  # adjust path if using Drive
df.head()

# 2. Setup translator
translator = GoogleTranslator(source="auto", target="en")
tqdm.pandas()

def safe_translate(text):
    if pd.isna(text) or not isinstance(text, str) or not text.strip():
        return text
    try:
        return translator.translate(text)
    except Exception:
        return text  # fallback if API rate-limits

# 3. Translate review text
df["data_en"] = df["data"].progress_apply(safe_translate)

# 4. Optional: rename columns for your project
df = df.rename(columns={"data_en": "review_en"})

# 5. Save translated dataset
df.to_excel("/content/testData_translated.xlsx", index=False)
print("Saved → /content/testData_translated.xlsx")