# -*- coding: utf-8 -*-
"""remove other and no aspect rows

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16R6FfzgGORwcBLSSTuA-NyMqUUIR0eZH
"""

import pandas as pd

# Load CSV
from google.colab import files
uploaded = files.upload()  # select testData_translated.csv or reviews_long_absa_msr.csv

# Load dataset
df = pd.read_csv(list(uploaded.keys())[0], encoding='latin1')

# Aspect columns
aspect_columns = [
    "stayingpower", "texture", "smell", "price",
    "colour", "shipping", "packing"
]

# Normalize text (optional but recommended)
# df[aspect_columns] = df[aspect_columns].apply(
#     lambda x: x.astype(str).str.lower().str.strip()
# )

valid_sentiments = {"positive", "negative", "neutral"}

# Keep rows with at least ONE valid aspect sentiment
df_filtered = df[
    df[aspect_columns].apply(
        lambda row: any(val in valid_sentiments for val in row),
        axis=1
    )
]

# Save cleaned dataset
df_filtered.to_csv("dataset_aspect_cleaned.csv", index=False)

print(f"✅ Original rows: {len(df)}")
print(f"✅ Rows after filtering: {len(df_filtered)}")
print("Cleaned dataset saved as dataset_aspect_cleaned.csv")